---
output:
  html_document: default
  pdf_document: default
params: 
    set_title: "Rapport d'élevage"
    s: na
    j: na
    pop: na
    poids: na
---
# Introduction

Dans le cadre du module optionnel "OPEN", nous avons constitué un groupe de 7 étudiants, et réalisé une application avec le package Shiny, disponible sous le logiciel R. Nous n'avions pas de contraintes pour réaliser notre application : nous étions libre de créer l'application que nous souhaitons. Nous avons décidé de partir sur la base d'une application réalisée dans le cadre de la découverte de Shiny cette semaine, et d'aller plus loin. Nous avons donc choisi l'application "Elevage de drosophiles" créée initialement par Vivien et Thibaut.

# Application envisagée

Cette application a pour objectif de comptabiliser des drosophiles dans un élevage et de faire varier des paramètres tels que différentes espèces de drosophile, le poids, le niveau de stress (qui augmente la reproduction) et le nombre de jour permettant d'élever une drosophile. 


### Production

En termes de production on souhaite observer à partir de combien de jour d'élevage avec une population de x individus de l'espèce x on peut esperer produire x g de matière sèche.

### Reproduction

En termes de reproduction, le but est de péréniser l'élevage la répatition Male/Femelle.
Enfin, en termes d'analyses annexes, on souhaite observer le nombre d'individus avec un potentiel génétique intéressant (yeux bleus).

### Autre débouchés

Le nombre d’individus avec un potentiel génétique intéressant (yeux bleus) leur permettant de servir d’animal de compagnie est de x.

# Application réalisée

Nous avons donc réalisée une application permettant à l'utilisateur (un éléveur de mouche) de gérer son élevage.
L'utilisateur peut renseigner grâce à des curseurs le nombre de mouches de son élevage, le nombre de jours d'élevage et le niveau de stress de ses mouches. Lorsque l'éleveur renseigne ces trois curseurs, l'application modélise un histogramme de répartition des poids des mouches de l'élevage (en mg) au jour J, prenant en compte leur niveau de stress. Cette histogramme suit une loi normale.
Enfin, une liste déroulante permet à l'éleveur d'informer l'application de la race qu'il élève. Cette information permet ensuite d'estimer la proportion de mâle et de femelle dans l'élevage. 

Nous  avons choisi de rajouter une option à la fin de notre rapport qui  permette de générer un rapport. Le but de celui-ci est de générer un  fichier qui puisse être conservé et qui fasse référence à des paramètres  choisis. Par exemple, nous pourrions vouloir observer les différences  de poids pour chaque espèce donnée, avec 100 mouches, 2 jours d'élevage et niveau de stress à 1. Ou bien, au sein d'une même espèce, conserver  nos observations pour un niveau de stress à 1 ou à 5.
 Un bouton "Générer un rapport" s'affiche donc en bas de l'application. Lorsuqe l'on clique dessus, cela entraine la création d'un rapport.Rmd. Ce rapport doit être enregistré dans le même dossier que celui dans lequel se trouve l'application Shiny. On peut alors l'ouvrir : un rapport en html s'ouvre, et permet d'afficher les informations essentielles que l'on souhaite enregistrer, re consulter plus tard et analyser. 
 
 
# Difficultés rencontrées
 
### Création du bouton "Générer un rapport". 

Nous avons donc rechercher un input "downloadbutton" dans la Gallery R Shiny, ainsi que l'output permettant de générer un rapport et le code correspondant. Après de nombreux essais sans réussite, nous avons compris qu'il nous manquait une partie : dans la partie server nous faisons effectivement référence à un rapport.Rmd. Ce rapport nous sert en réalité de base pour l'affichage des données de Shiny en Rmarkdown. Il s'agit ainsi de paramétrer chaque input/output que l'on souhaite faire apparaître dans le rapport final dans le rapport.Rmd. Cela peut sembler anecdoctique mais il nous a fallu en réalité beaucoup de temps pour régler ce problème. Une des parties les plus chronophages a été d'adapter le code de la Gallery à notre code déjà existant sans oublier de parenthèses ou de virgules, ce qui empêchait l'application de fonctionner. 

### Fichier CSV


Dans un premier temps, ce fichier contenait des informations de base sur les caractéristiques des différentes espèces (poids au jour 0, la croissance, la moyenne de poids et l'écart type) permettant ensuite de tracer l'histogramme.
Le fichier csv a ensuite été modifié : seuls les noms d'espèce de mouches ont été gardés pour alléger le code. Le reste des informations ont donc été rentrées en dur sur R. 
Nous avons rencontrés des problèmes pour charger le fichier csv dans le code avec la fonction read.table car nous l'avion d'abord placé dans le fichier app. Nous avons résolu le problème en le plançant juste en amont de la partie ui. 

# Conclusion

La création de cette application nous a permis de mettre en pratique les différents documents explicatifs traitant du package Shiny que nous avons pu lire. Cela nous a permit d'intégrer plus facilement certaines notions, mais également de se confronter à de multiples problèmes qu'il nous a fallu résoudre. Nous avons dû également utiliser tous les moyens à disposition pour réussir à coordonner un grand groupe de travail comme le notre. Pour cela, nous avons utilisé GitHub pour héberger notre travail, et permettre d'avoir une vue sur les modifications de notre travail. Nous avons également utilisé l'Etherpad de l'ISARA, nous permettant de créer un document texte partagé. Enfin, nous avons utilisé le Chat Isarien, qui nous a été très utile pour communiquer directement entre les membres du groupes. Grâce à ses différents outils, chaque membres du groupe à pu travailler en étroite collaboration sans perdre de temps en communication. 
